language: node_js
node_js:
- "8"
cache:
  directories:
  - "node_modules"
env:
  global:
    secure: "fiAf3fswcydsvRweQXeJy3pr31vcEWyjlCMCJgBTB0TV37QzmsNN7MbFzz55vyGZbIB600qwP7dOjhZaFv/1myEp4nPrrYdf+RRMfPp5VCH3MzASMICb4ZcBHyOIb2IMdltmpi7IPQuCVObhsNVlhMK1RJIzNfYo4StsffjIBV7bVg0x5b2Ig3H3eiJKBpYB2+vmdqpHgHJtPArSG3cgQIpEm7oxpivLrhIHe9jKL9wK1x4JIO2EG+QlukDJsilXllhBVf5oVEMshOSdTNcL/cFJ1VpMbsiZoubdK3DbTNFJSt3UALoCgasO/vYUruXjxzb0uN1HGEYPbDSfeTu194RgdNaZp4VYVZzAtBWJ21RV1bFu7Pfr2BjtID5DohznnXeE2wXWK6pLHOqTLW9FHvOmA5W/tia6emjlgSg0EZhaXipnR7sinf0i+Iuxbj9Y/yWE3YTAbkXyHD4b5q6d5WackprquRQvWwaYF2P4oHxykQFtWEKelan4NyjkAyYLdAWn1QITJVtdk7NmuDJ7cu/bre7lLuQMFzh50ZnQc8Fc1+7QTxiC8eJj8gVa1IvrMlN81DOoRz28u9O0uFkEk4jN0xR6xFjIpS0MvhmlnkTC7wQ2ObtMD7sItdtTyi4NFMQR4nSWQrobbzNd6aUOikVUplceQ74+Qjptwqhr0lM="
branches:
  only:
  - master
before_script:
- npm i -g firebase-tools
- npm install
script:
- ng build --prod --base-href /en-us/
- ng build --prod --configuration=production-fr-ch --base-href /fr-ch/
- cp src/404.html dist/404.html
deploy:
  provider: firebase
  token:
    secure: "f0tQrIYmkEX5eDAsDm3JitR11FbIADmGLThU5dBojDPNDNcTnPtq45SFzIc6jjDfWk2Zh90j5eRw76jpkeHAU0TzOXkGG46IiGMeygcYzJDr1n96btst807y5b0tswdJGE3S26lcOH32YMhY3td+sUu3AT94rn0whdWoKW+9P+GNRCdaujNSdJL1NxfGgI2oVjbXTGd+hVQ4RL7EM30WJzKao1RnP7q7Bd5ZNMBbkhzCch5lfzyARSagUXLxNTV+vBgFlSHmCNW6agmOxDOagfryYycM6oruWo+ceVQr+6KJ/ynr8bh03KYKZfXE0lJkw/3s1lp1Bty8SJpLxIm1Ymkqyad1fDBNwWMM7zNw/qVDwbBK7+hEaL+hlfFTfBxPWzAhJH+mIBNWHD09g22gJLaQsyJjWIytSPSgh6YDVOb/hnNrUevWcDl1FivMSD/2Zl9x2+6tW4MEsrFYM+0x4g9h7CG4ednkdn81X4ltQGIR0KEuWNh1+LRFChohEyUomUUTktitE01vrmss94O/Hwyvt9VJvEuE4M0D7xTAaPLs7mXWiw5d2UxGkMd+XB7ecoOb1jqZ03/mM4M1YFXLKtdCRceQgqQwBmzH5LKsZ31ZwP4JWPBwiooqmEcG5yylyiDfkT7gDnVdSAtodMHEU7QTkHFbDk4w/OvIHVX1eBs="
    skip_cleanup: true
    on:
      branch: master
