language: node_js
node_js:
- "8"
cache:
  directories:
  - "node_modules"
env:
  global:
    secure: moYE3nxW4565EZNv1jZx6S7mA6UXAA87/ujAOMjRMQ0zRH6G/fO6O/QIdXC1ldhT1XOCP3FAnV50de+FuPnWq9i1QB5A9R9B3iRWWwJ9uARYQv18iIVrcS4ibjJvwbhLp1B7YSN/z+SJLnHr4vW6soZaqTCK2O0SWiCvvIckD/d+efSuJiqZT985iJQdoiLddHC8guH9Qly7TGrowOmvxjAQiqC/9hxSVnWj1OCU2tQVGGS7q6lnJZ8PNvlkpsD1PaIRt/6YWQpV2JtE+ZZH8N9QCY4HOfcMOu8G5co5GoXoJl9Ihn1KqBxQcuhUpM0JXbUj11M5hV05Ure3BkNwv63eHVIwzGBFdpJt7jQfhhmYud2NQkHcoa0xZqbVED6Kw+70L/1GguEmBP6gljeirPb8MddjMGKPzO+9u1BkcmrAHYUl1bwxU2miZY+xBqTIo5eOY1EN18yhZZGOLQ0e7udDtyts/RR1VW7dG+kbrWS18I2llGOCQGqYxeGtk9JPZ+kgIOcZLZUin9RTxagJV3GAF8GBgmT5udwPlV2hXi2CP9A7cRg8Lw+h8P36oUseXm9Ztb3LZ2/HjicNdMQPwhpQsYYmQZHBqnzeH03JpngnWBcyW+SCLwNIXXVnem0C79BWS5cO8s2o66qo+JpiFEPgWYIqNo/FKaxNPudiRkA=
branches:
  only:
  - master
before_script:
- npm i -g firebase-tools
- npm install
script:
- git checkout master
- ng build --prod --base-href /en-us/
- ng build --prod --configuration=fr-ch --base-href /fr-ch/
- cp src/app/404.html dist/404.html
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
    skip_cleanup: true
    on:
      branch: master
