language: node_js
node_js:
- "8"
cache:
  directories:
  - "node_modules"
branches:
  only:
  - master
before_script:
- npm install
script:
- git checkout master
- ng build --prod --base-href .
- cp dist/ooptical-ui/index.html dist/ooptical-ui/404.html
deploy:
  provider: firebase
  token:
    secure: "$FIREBASE_TOKEN"
    skip_cleanup: true
    on:
      branch: master
