language: node_js
node_js:
- "8"
cache:
  directories:
  - "node_modules"
branches:
  only:
  - master
before_script:
- npm i -g firebase-tools
- npm install
- cd functions
- npm install
- cd ..
script:
- git checkout master
- ng build --prod --base-href /en-us/
- ng build --prod --configuration=production-fr-ch --base-href /fr-ch/
- cp src/404.html dist/404.html
- firebase deploy --token=$FIREBASE_TOKEN
