language: node_js
node_js:
- "8"
cache:
  directories:
  - "node_modules"
branches:
  only:
  - master
before_script:
- npm i -g firebase-tools
- npm install
script:
- ng build --prod --base-href /en-us/
- ng build --prod --configuration=production-fr-ch --base-href /fr-ch/
- cp src/404.html dist/404.html
deploy:
  provider: firebase
  token:
    secure: "cHXpMuFqdT4WZ3RSTz+jWG91fQ8P236hLT7ntOPtVu17xOPZ9MVT+AmGp8tGBb18fPKlLYwVtVNLhDIUt3n9Z4Z74Eh4Z7LPqip0wpi3rRUZIrd8/gCBjJHPglhL1GiYZ7qinUI1TCQO8m0WnAJAqAh79jPOI9IvSgIzX9blKg/CmQX1GAwPZ1HZH2EPU++ogvEToLkTXttRoQFNg/rB3Q7iUY8QZJ2SMT/Q3JduIqwvcZ4JUq2bCRyIUsw5DihLDUBV4O2dRTYoRW+eVa6XUdd01YJH7IlTrPymzyWUlmiwAMEkJMLzW5a+AVw/I8KBhX8Afx3bX0rLbbWhQsriOFFY1A244jIFRnHDqaUA7HQcPkVT8kUBxftvbUd7k0hkZIAizjSZfEbloOXKoKOkOouGZ9XNIdWb5duENI0RgI65FdZ+tLWFdbVlNV3ra30ccfFFgOFG3pRhdKiIHM00dPHYYSFB6sNGTHSyKgl2uLaMnWQcyEAshWZXekR4lB5p5Vf6P2yTvkeGIuiyS4aJeuCmIuUWtF6j+rTpFeWwmeQhh5aTEnd4c3RwIfLy9MqrUAOiSDLFeYPfMh/OOIbH0dXXLyD6YIiO9ZlffRwi3AKa9bKSGrX5sS8VuDQBy26B4ghOkS7OxDplj2jfkr9+/v5rgPUYCa1i20AgXMtRamE="
    skip_cleanup: true
    on:
      branch: master
